### ISSUE TITLE
No map found

### ISSUE THREAD

**Issue by PhilippKrone** [teamrota/react-native-gmaps#1]
Hello,

I get a redbox basically telling me that 

````javascript
      map.getUiSettings().setMyLocationButtonEnabled(false);
````

crashed the app as "map" is null. I wonder whether there has to be some kind of check in here whether map is actually not null? This might be the case for several reasons: http://stackoverflow.com/questions/22471766/android-mapview-getmap-returns-null

Regards
Philipp

**Comment by kirkness** [comment]
Thanks for this Phillipp. Could you confirm; is the map null because you don't have the google play apk installed?

I'll add in the check for the map being null.

**Comment by PhilippKrone** [comment]
Currently investigating that. 

It would be nice to have a function with a callback like:

````javascript
NativeModule.GMaps.canOpenMaps((success) => {if (!success) { ..<do whatever the app wants to do in this case> }});
````

**Comment by PhilippKrone** [comment]
@kirkness Indeed after installing the APK (following http://stackoverflow.com/questions/20121883/how-to-install-google-play-services-in-a-genymotion-vm-with-no-drag-and-drop-su), it is loading the map :)

**Comment by kirkness** [comment]
Awesome; I'll update the readme and add a null check for now - thanks for your help.
