### ISSUE TITLE
Update to work with RN 0.16.0

### ISSUE THREAD

**Issue by mangogogos** [teamrota/react-native-gmaps#14]
Currently not working 0.16, first error encountered attached:

![screen shot 2015-12-11 at 3 34 20 pm](https://cloud.githubusercontent.com/assets/10715768/11758162/c2761e3c-a01c-11e5-9822-389391894b4b.png)

**Comment by FlorentD** [comment]
+1

**Comment by jason-c-child** [comment]
+1

**Comment by christocracy** [comment]
The problem is related to [this](https://github.com/facebook/react-native/issues/4605)

**Comment by christocracy** [comment]
I have successfully merged @timhagn [fork](https://github.com/timhagn/react-native-gmaps) into this version and have it working with react-native 17.  I will send a PR to this repo asap.

**Comment by mangogogos** [comment]
Cheers!
