### ISSUE TITLE
iOS Support for Google Maps SDK

### ISSUE THREAD

**Issue by EricPKerr** [teamrota/react-native-gmaps#27]
It would be great to have an iOS version of the Google Maps SDK.  The current `index.ios.js` file shows an error message when it loads suggesting to use the default React Native built-in Apple Maps `MapView` component.

Any plans to include support for the iOS Google Maps SDK? There don't seem to be any good ports yet.

**Comment by shukerullah** [comment]
+1

**Comment by edward-at-intelex** [comment]
+1 as well. thanks

**Comment by edward-at-intelex** [comment]
just an additional note, the mapview component on the reactnative site is still in its infancy, appearing to support iOS (I am investigating) but not android.

**Comment by arashbi** [comment]
@edward-at-intelex I couldn't get it to work with android either.

**Comment by harrygreen** [comment]
+1

**Comment by lwinkyawmyat** [comment]
+1

**Comment by 7mllm7** [comment]
+1

**Comment by jjzazuet** [comment]
+1
