### ISSUE TITLE
Current Location

### ISSUE THREAD

**Issue by shukerullah** [teamrota/react-native-gmaps#28]
Is there any way to start map with current location? Thanks

**Comment by timhagn** [comment]
@shukerullah As (not that clearly, I agree) stated in README.MD: center={ { lng: 0.1, lat: 51.0 } } - here you can start up with your location received by a Location Provider of choice (Geolocation Polyfill for example).

**Comment by shukerullah** [comment]
Thanks for response, I already did it with Geolocation.
